config/routes.rb
KidsBank::Application.routes.draw do
  resources :transactions
  resources :accounts
  root "accounts#index"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    resources :settings
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  source Rails.root.join("config/app.yml")
  namespace Rails.env
end

app/controllers/admin/settings_controller.rb
module Admin
  class SettingsController < ApplicationController
    before_action :get_setting, only: [:edit, :update]

    def index
      @settings = Setting.get_all
    end

    def edit
    end

    def update
      if @setting.value != params[:setting][:value]
        @setting.value = params[:setting][:value]
        @setting.save
        redirect_to admin_settings_path, notice: 'Setting has updated.'
      else
        redirect_to admin_settings_path
      end
    end

    def get_setting
      @setting = Setting.find_by(var: params[:id]) || Setting.new(var: params[:id])
    end
  end
end

app/views/admin/settings/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= simple_form_for(@setting, url: admin_setting_path(@setting.var), method: 'patch') do |f| %>
    <div class="form-inputs well">
      <%= f.input :value, as: :string, :label => "#{@setting.var}" %>
    </div>

    <div class="form-actions">
      <%= f.submit "Сохранить", :class =>'btn btn-primary' %>
    </div>
<% end %>


</div>
</div>

app/views/admin/settings/edit.html.erb
<%- model_class = Setting -%>
<h3 class="text-info strong page-header">Панель редактирования опций <small> <%= link_to "<< Вернуться на главную", admin_root_path, class: "btn btn-sm btn-default pull-right" %>
    </small></h3>
    
    <%= render :partial => 'form' %>

app/views/admin/settings/index.html.erb
<h3 class="text-info">Панель редактирования опций <small> <%= link_to "<< Вернуться на главную", admin_root_path, class: "btn btn-sm btn-default pull-right" %>
    </small></h3>

    <hr/>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
<div class="panel panel-danger">
  <div class="panel-heading"> Конфигурация
  </div>
  <div class="panel-body">

    <table class="table table-stripe table-hover">
      <tr>
        <th>Опция</th>
        <th>Значение</th>
        <th></th>
      </tr>
      <% Setting.find_each do |s| %>
      <tr>
        <td><%= s.var %></td>
        <td><%= s.value %></td>
        <td><%= link_to 'Редактировать', edit_admin_setting_path(s.var), class: "btn btn-sm btn-primary"  %></td>
      </tr>
      <% end %>
    </table>
    </div>
  </div>
  </div>
  </div>

app/views/admin/settings/new.html.erb
<%- model_class = Setting -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/settings/show.html.erb
<%- model_class = Setting -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:var) %>:</strong></dt>
  <dd><%= @setting.var %></dd>
  <dt><strong><%= model_class.human_attribute_name(:value) %>:</strong></dt>
  <dd><%= @setting.value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:thing_id) %>:</strong></dt>
  <dd><%= @setting.thing_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:thing_type) %>:</strong></dt>
  <dd><%= @setting.thing_type %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              settings_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_setting_path(@setting), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              setting_path(@setting),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>