config/routes.rb
KidsBank::Application.routes.draw do
  resources :transactions
  resources :accounts
  root "accounts#index"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    resources :settings
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  
# Relations
has_many :posts
has_many :transactions
has_many :accounts  
# Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable #, :confirmable

  # Pagination
  paginates_per 100

  # Validations
  # :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def self.paged(page_number)
    order(admin: :desc, email: :asc).page page_number
  end

  def self.search_and_order(search, page_number)
    if search
      where("email LIKE ?", "%#{search.downcase}%").order(
      admin: :desc, email: :asc
      ).page page_number
    else
      order(admin: :desc, email: :asc).page page_number
    end
  end

  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","email","created_at")
  end

  def self.last_signins(count)
    order(last_sign_in_at:
    :desc).limit(count).select("id","email","last_sign_in_at")
  end

  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_action :set_user, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]


  def index
    @users = User.search_and_order(params[:search], params[:page])
  end

  def show
    redirect_to edit_admin_user_path(params[:id])
  end
 
  def new
    @user = User.new
  end

  def edit
  end
 
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save!
        format.html { redirect_to [:admin, @user], notice: 'Оператор успешно создан' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    old_email = @user.email
    new_params = user_params.dup
    new_params[:email] = new_params[:email].strip

    @user.email = new_params[:email]
    @user.first_name = new_params[:first_name]
    @user.last_name = new_params[:last_name]
    @user.mobile = new_params[:mobile]
    @user.position = new_params[:position]
    @user.about = new_params[:about]
    @user.password = new_params[:password] if new_params[:password].strip.length > 0
    @user.password_confirmation = new_params[:password_confirmation] if new_params[:password_confirmation].strip.length > 0
    if current_user.id != @user.id
      @user.admin = new_params[:admin]=="0" ? false : true
      @user.locked = new_params[:locked]=="0" ? false : true
    end

    if @user.valid?
     # @user.skip_reconfirmation!
      @user.save
      redirect_to admin_users_path, notice: "#{@user.email} updated."
    else
      flash[:alert] = "#{old_email} couldn't be updated."
      render :edit
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  rescue
    flash[:alert] = "The user with an id of #{params[:id]} doesn't exist."
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(
    :email,
    :password,
    :password_confirmation,
    :first_name,
    :last_name,
    :mobile,
    :position,
    :about,
    :admin,
    :locked
    )
  end

end

app/views/admin/users/edit.html.erb
<% title("Профайл пользователя: #{@user.id}") %>
<div class="row">
  <div class="col-sm-6">
    <h3>
      Профайл оператора <small><%= "#{@user.email} - id: #{@user.id}" %></small>
    </h3>
    <p><%= link_to "Back to Users", admin_users_path, class: "btn btn-default" %></p>

    <%= form_for [:admin, @user], :html => { :role => "form" } do |f| %>

    <div class="form-group">
      <%= f.label :email %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Пароль" %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Подтвердите пароль" %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label  "Имя" %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label "Фамилия" %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label "Телефон" %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :mobile, class: "form-control" %>
        </div>
      </div>
    </div>
    
    
    
    <div class="form-group">
      <%= f.label "Должность" %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :position, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.label "Дополнительная информация" %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_area :about, class: "form-control" %>
        </div>
      </div>
    </div>
    
    
    
    <% unless current_user.id == @user.id %>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <%= f.check_box :locked %> <%= f.label :locked, "Is Locked?" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <%= f.check_box :admin %> <%= f.label :admin, "Is Admin?" %>
        </div>
      </div>
    </div>
    <% end %>

    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Сохранить", class: "btn btn-danger" %>
      </div>
    </div>

    <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<% title("Админ панель операторов") %>
<h3 class="text-info">Учетные записи операторов <small>создание новых, удаление или редактирование учетных записей операторов</small></h3>
<hr/>
<p><%= link_to "<< Вернуться на главную", admin_root_path, class: "btn btn-sm btn-default" %></p>

<div class="text-center">
  <p><%#= page_entries_info @users %></p>
  <%#= paginate @users %>
</div>

<%= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
<p class="well">
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Поиск", :name => nil, class: "btn btn-sm btn-primary" %>
  <%= link_to "Показать всех операторов", admin_users_path, {class: "btn btn-sm btn-link"} %>
</p>
<% end %>
<br>


<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Список операторов</div>
  <div class="panel-body">
  
  </div>

  <!-- Table -->
<table class="table table-striped">
  <tr>
    <th>#</th>
    <th>Email</th>
    <th>Админ</th>
    <th>Заблокирован</th>
    <th>К-во входов</th>
    <th>Создан</th>
    <th>Посл. вход</th>
    <th>IP п-го входа</th>
  </tr>

  <% @users.each do |user| %>

  <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.email, admin_user_path(user) %></td>
    <td><%= user.admin? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.locked? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.sign_in_count %></td>
    <td><%= time_ago_in_words(user.created_at) %></td>
    <% unless user.last_sign_in_at.nil? %>
    <td><%= time_ago_in_words(user.last_sign_in_at)%> ago</td>
    <% else %>
    <td>never</td>
    <% end %>
    <td><%= user.last_sign_in_ip %></td>
  </tr>

  <% end %>

</table>

  </div>
  <br /> 
<%= link_to "Добавить Оператора", new_admin_user_path, class: ' btn btn-sm btn-primary' %>
  <div class="text-center">
  <p><%#= page_entries_info @users %></p>
  <%= paginate @users %>
</div>

app/views/admin/users/new.html.erb
<div class="row">
  <div class="col-sm-6">
    <p><%= link_to "Back to Users", admin_users_path %></p>

    <%= form_for [:admin, @user], :html => { :role => "form" } do |f| %>

    <div class="form-group">
      <%= f.label :email %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>

  
    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Создать", class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>

  </div>
</div>