config/routes.rb
KidsBank::Application.routes.draw do
  resources :transactions
  resources :accounts
  root "accounts#index"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    resources :settings
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  # relations
  CARD_TYPES = [ "Пластиковая КЛ", "Бумажная КЛ", "ВТБ" ]
  OPERATIONS = [ "Пополнение", "Снятие" ]  
  
  has_many :transactions
  belongs_to :user
  paginates_per 50 
  

  validates :balance, :first_name, :last_name, :card_type,   presence: true 
  validates :balance, numericality: { only_integer: true }
  validates :card_number, uniqueness: true
  # include PublicActivity::Model
 # tracked owner: Proc.new { |controller, model| controller.current_user ? controller.current_user : nil }
  
   #has_many :cards , dependent: :destroy


  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /accounts
  # GET /accounts.json
  def index
     params[:q] ||= {}
    if params[:q][:created_at_lteq].present?
      params[:q][:created_at_lteq] = params[:q][:created_at_lteq].to_date.end_of_day
    end
    if params[:q][:created_at_gteq].present?
      params[:q][:created_at_gteq] = params[:q][:created_at_gteq].to_date.beginning_of_day
    end   
      @q = Account.ransack(params[:q])
      @accounts  = @q.result
      @total_balance = 0
      @total_paper = 0
      @total_vtb = 0
      @total_plastic = 0
      @total_accounts = 0 
      @accounts.find_each do |a|
         @total_accounts += 1 
         @total_balance += a.balance
         
          case a.card_type
          when   "Пластиковая КЛ"
            @total_plastic += 1  
          when "Бумажная КЛ"             
            @total_paper += 1
          when "ВТБ"
            @total_vtb += 1
          end
      end  
      
      @accounts  = @accounts.page(params[:page]) 
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
   # @account.card_number = [*('a'..'z'),*('0'..'9')].shuffle[0,8].join
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account      = Account.new(account_params)
    @account.user = current_user
    @transaction  = @account.transactions.build( :user_id => current_user.id, :amount => @account.balance,
                                                :transaction_type => Account::OPERATIONS.first,
                                                :account_id =>  @account.id      )
    respond_to do |format|
      if @account.save
       #   @transaction.save
        #  @transaction = @account.transactions.new
     #  @transaction.user_id = current_user.id
     #  @transaction.amount = @account.balance
     #  @transaction.transaction_type = Account::OPERATIONS.last
     #  @transaction.save

        format.html { redirect_to @account, notice: 'Новый аккаунт успешно создан' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
#   def put_money_on
#     respond_to do |format|
#      #binding.pry
#       if @account.update(account_params)
#         format.html { redirect_to @account, notice: 'Account was successfully updated.' }
#         format.json { render :show, status: :ok, location: @account }
#       else
#         format.html { render :edit }
#         format.json { render json: @account.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#   # POST /accounts.json
#   def put_money_on
#     @account = Account.new(account_params)

#     respond_to do |format|
#       if @account.save
#         format.html { redirect_to @account, notice: 'Account was successfully created.' }
#         format.json { render :show, status: :created, location: @account }
#       else
#         format.html { render :new }
#         format.json { render json: @account.errors, status: :unprocessable_entity }
#       end
#     end
#   end
# def


  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Аккаунт был успешно обновлен' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end


 
  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Аккаунт был успешно удален' }
      format.json { head :no_content }
    end
  end

 
 
  private
    
    def load_activities
      @activities = PublicActivity::Activity.order('created_at DESC').limit(20)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit! #(:card_number, :last_name, :first_name, :middle, :dob, :balance)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account_history.html.erb
<%- @account.transactions.find_each do |transaction| %>
  <div class="panel panel-default">
    <div class="panel-heading"><strong><%= link_to "transaction##{transaction.id}", transaction_path(transaction) %></strong>
     сделана 
     <%= link_to "#{transaction.user.email}", admin_user_path(transaction.user) %>
      <strong class="text-muted pull-right"> <%= transaction.created_at.strftime("%d/%m/%Y %H:%M") %> </strong>
    </div>
  <div class="panel-body"> 
  <dl class="dl-horizontal">
  <dt><strong>Сумма транзакции:</strong></dt>
  <dd><%= transaction.amount rescue '-'%></dd>
  <dt><strong>Тип транзакции:</strong></dt>
  <dd><%= transaction.transaction_type rescue '-'%></dd>
  <dt><strong>Номер карты:</strong></dt>
  <dd><%= transaction.account.card_number rescue '-'%></dd>
  <dt><strong>Тип карты:</strong></dt>
  <dd><%= transaction.account.card_type rescue '-'%></dd>
</dl>
 </div>
 </div>
<% end %>

app/views/accounts/_account_info.html.erb
<div class="panel panel-default">
      <div class="panel-heading"> <h5> Информация о клиенте </h5> </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-7">
            <dl class="dl-horizontal">
              <dt><strong>Номер карты:</strong></dt>
              <dd><%= @account.card_number %></dd>
              <dt><strong>Тип Карты:</strong></dt>
              <dd><%= @account.card_type %></dd>
              <dt><strong>Фамилия:</strong></dt>
              <dd><%= @account.last_name %></dd>
              <dt><strong>Имя:</strong></dt>
              <dd><%= @account.first_name %></dd>
              <dt><strong>Отчество:</strong></dt>
              <dd><%= @account.middle %></dd>
              <dt><strong>Возраст:</strong></dt>
              <dd><%= @account.age %></dd>
              <dt><strong>Баланс:</strong></dt>
              <dd><%= @account.balance %></dd>
              <dt><strong>День Рождения:</strong></dt>
              <dd><%= @account.dob.strftime("%d/%m/%Y") rescue '-'%></dd>
              <dt><strong>Дата создания аккаунта:</strong></dt>
              <dd><%= @account.created_at.strftime("%d/%m/%Y %H:%M") %></dd>
              <dt><strong>Оператор:</strong></dt>
              <dd><%= @account.user.email %></dd>
            </dl>
          </div>
          
          <div class="col-md-5 well">
            <%= simple_form_for @account.transactions.new, :html => { :class => 'form-horizontal ' } do |f| %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :account_id, value: @account.id %>
              <%= f.input :amount,  label: 'Сумма транзакции', required: true, input_html: { min: '0' } %>
              <%#= error_span(@transaction[:amount]) %>
              <%= f.input  :transaction_type, label: 'Тип транзакции', collection: Account::OPERATIONS, include_blank: false %>
              <%#= error_span(@transaction[:transaction_type]) %>
              <%= f.button :submit,"Утвердить", :class => 'btn-primary' %>
              <%#= link_to t('.cancel', :default => t("helpers.links.cancel")),
                          transactions_path, :class => 'btn btn-default' %>
            <% end %>
          </div>
        </div>
          <hr>
      <% if current_user.admin? %>              
        <%= link_to "Редактировать",
                  edit_account_path(@account), :class => 'btn btn-default' %>
        <%= link_to   "Удалить",
                  account_path(@account),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
      <% end %>
    </div>
    </div>

app/views/accounts/_form.html.erb
<div class="col-md-6 col-md-offset-3"  data-no-turbolink="true">
  <div class="panel panel-default ">
    <div class="panel-body">
      <%= simple_nested_form_for @account, :html => { :class => 'form-horizontal col-md-12' } do |f| %>
        <%= f.input :card_number, label: 'Номер карты', :required => true %>
        <%= f.input :card_type, collection: Account::CARD_TYPES, selected: Account::CARD_TYPES[1] , label: 'Тип карты'%>
        <%= f.input :last_name, label: 'Фамилия' %>
        <%= f.input :first_name , label: 'Имя'%>
        <%= f.input :middle , label: 'Отчество' %>
        <%#= f.input :dob, as: :string, label: 'Дата Рождения', input_html: {type: :date} %>
        <%-  f.object.dob = "31/12/2012" if f.object.dob? == false  %>
        
        <%= f.input :dob, as: :string, label: "День Рождения" , input_html: { id: 'dob_box',:value => localize(f.object.dob, format: "%d/%-m/%Y") || "10/10/2010"  }, 
               placeholder:'12/29/1998', start_year: Time.now.year - 20, end_year: Time.now.year - 3, order: [:day, :month, :year] %>

               <%= f.input :age,  label: 'Возраст'  ,:include_blank => true, input_html: { min: '3', max: '16', id: 'age_box' }  %>
        <%= f.input :balance , label: 'Баланс Ландов', required: true,  input_html: { min: '0' } %>
      <%= f.button :submit, "Сохранить", :class => 'btn-primary' %>
      <%= link_to "Отмена", accounts_path, :class => 'btn btn-default' %>
      <% end %>
      </div>
    <div class="panel-footer">
    </div>
  </div>
  </div>

<script>
$( document ).ready(function() {

$('#dob_box').on('change', function () {
  
  date = $(this).val();
  age = getAge(date);
  $('#age_box').val(age);
});

$('#age_box').on('change', function () {
  date = $(this).val();
  var age = parseInt(date) 
  dob = getDob(age);
  $('#dob_box').val(dob);
});

function getDob(ageinteger) {
    var year = new Date().getFullYear();
    var birthyear = year - ageinteger;
    var dobstring = "31/12/"+ birthyear;
   // var dob = dob_string;
  //  var birthDate = new Date(dateString);
    //var birthDate = new Date(dateString);
    //var age = today.getFullYear() - birthDate.getFullYear();
    //var m = today.getMonth() - birthDate.getMonth();
    //if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
    //    age--;
   // }
    return dobstring;
}

function getAge(dateString) {
    var today = new Date();
    
    var birthDate = new Date(dateString);
    var age = today.getFullYear() - birthDate.getFullYear();
    var m = today.getMonth() - birthDate.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
        age--;
    }
    return age;
}

});
</script>

app/views/accounts/edit.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h3> Редактировать Аккаунт </h3>
</div>
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<div class="row">
  <div class="col-md-8">
<div class="panel panel-default">
  <div class="panel-heading"> База Данных Кидландии 
  
<%= link_to "Добавить аккаунт",
            new_account_path,
            :class => 'btn btn-primary btn-xs' %>
  
  </div>
  <div class="panel-body">
  <div class="pull-right">
    <%= page_entries_info @accounts %>
  </div >
    <%= paginate @accounts %>
    <table class="table table-stripe table-hover" data-no-turbolink="true">
      <thead>
        <tr>
          <th> <%= sort_link(@q, :card_number, '#', default_order: :desc) %></th>
          <th> <%= sort_link(@q, :card_type, 'Тип', default_order: :desc) %></th>
          <th> <%= sort_link(@q, :last_name, 'Фамилия', default_order: :desc) %></th>
          <th> <%= sort_link(@q, :first_name, 'Имя', default_order: :desc) %></th>
          <th> <%= sort_link(@q, :balance, 'LD', default_order: :desc) %></th>
          <th> <%= sort_link(@q, :created_at, 'Рег.', default_order: :desc) %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @accounts.each do |account| %>
          <tr>
            <td><%= link_to account.card_number, account_path(account) %></td>
            <td><%= account.card_type %></td>
            <td><%= account.last_name %></td>
            <td><%= account.first_name %></td>
            <td><%= account.balance %></td>
            <td><%= account.created_at.strftime("%d/%m/%Y") rescue '-'%></td>
            <td>
              
              <%= link_to "Операции",
                          account_path(account), :class => 'btn btn-primary btn-xs' %>
              <%= link_to "Ред.",
                          edit_account_path(account), :class => 'btn btn-default btn-xs' %>
              <%= link_to "Удалить",
                          account_path(account),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
   <div class="pull-right">
    <%= page_entries_info @accounts %>
  </div >
    <%= paginate @accounts %>
  </div>
</div>
  </div>

<div class="col-md-4">
  <div class="panel panel-default">
    <div class="panel-heading">Быстрый поиск</div>
    <div class="panel-body">
       <%= ransack_simple_form_for @q , :html => { :class => 'form-vertical ' } do |f| %>
        <%= f.input :last_name_or_first_name_or_card_number_cont, label: 'Фамилия, Имя, Номер' %>
        <%= f.button :submit, "Поиск", :class => 'btn-primary btn-block' %>
      <% end %>
    </div>
  </div>

  <hr/>

  <div class="panel panel-default">
    <div class="panel-heading">Детальный поиск</div>
    <div class="panel-body">
      <%= ransack_simple_form_for @q , :html => { :class => 'form-vertical ' } do |f| %>
    
        <%= f.input :card_number_cont , label: 'Номер Карты'%>
        <%= f.input :last_name_cont, label: 'Фамилия' %>

        <%= f.input :first_name_cont , label: 'Имя'%>
        
        
        <%= f.input  :user_id_eq ,:collection => User.all, :label_method => :email, :value_method => :id, :label => "Оператор" ,:include_blank => true %>
        <%= f.input  :card_type_eq ,:collection => Account::CARD_TYPES,  :label => "Тип карты" ,:include_blank => true %>
        <h5><strong class="text-info">Созданы в период:</strong></h5> 
        <div class="alert alert-info">
          <%= f.input  :created_at_gteq, as: :date,  :label => "От:" ,:include_blank => true, class: 'form-control  '%>
          <%= f.input :created_at_lteq, as: :date,   :label => "До:" ,:include_blank => true, class: 'form-contol'  %>
        </div>
            
        <h5><strong class="text-info">По дате рождения:</strong></h5> 
        <div class="alert alert-info">
          <%= f.input :dob_gteq, as: :date,  :label => "От:" ,:include_blank => true, class: 'form-control  '%>
          <%= f.input :dob_lteq, as: :date,   :label => "До:" ,:include_blank => true, class: 'form-contol'  %>
        </div>
        <div class="row">
          <div class="col-md-6">
            <%= f.input :balance_gteq , label: 'Баланс от'%>
          </div>
          <div class="col-md-6">
            <%= f.input :balance_lteq , label: '- до'%>
          </div>
        
        </div>
            <%= f.button :submit, "Поиск", :class => 'btn-primary btn-block' %>
      <% end %>
    </div>
  </div>
  
   
  <%- if current_user.admin? %> 
  <div class="panel panel-default">
    <div class="panel-heading">Аналитика</div>
    <div class="panel-body">
      <dl class="dl-horizontal">
        <dt><strong>К-во аккаунтов:</strong></dt>
        <dd><%= @total_accounts %></dd>
        <dt><strong>Сумарный баланс:</strong></dt>
        <dd><%= @total_balance %></dd>
        <dt><strong>К-во "Бумажных КЛ":</strong></dt>
        <dd><%= @total_paper %></dd>
        <dt><strong>К-во "Пластиковых КЛ":</strong></dt>
        <dd><%= @total_plastic %></dd>
        <dt><strong>К-во "ВТБ":</strong></dt>
        <dd><%= @total_vtb %></dd>
      </dl>
    </div>
  </div>
  </div>
<% end %>



</div>

app/views/accounts/new.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h3> Создание нового аккаунта </h3>
</div>
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<div class="row">
  <div class='col-md-7'>
    <%= render 'account_info' %>
  </div>
  <div class='col-md-5'>
    <%= render 'account_history' %>
  </div>
<div>
    
    
  